# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aec8c1fd041b0656393bd54efb4bb701abf63020ee530e7aad58f5fc258de5cc70ac4bf26d0644f34f5fdb281f6d1e81c40161034d5ffdf8ced016787676f11e

test:
  secret_key_base: 9445ec9f753ff02048c56744cb22da77d6ac735414b7490f44cae224c13d9e62b79eb9776ed7d5a7006a0df5991cb64f8849ce294220b71335300fad27a78c7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
